import type {
  ProjectDocumentation,
  FileDocumentation,
  DocumentedSymbol,
} from "../../types/index.js";

/**
 * 프로젝트 문서를 llms.txt 형식으로 생성한다.
 * https://llmstxt.org 스펙 기반, AI/LLM 컨텍스트 최적화.
 * @param project - 프로젝트 문서
 * @param options - 생성 옵션
 * @returns llms.txt 형식 문자열
 */
export function generateLlmsTxt(
  project: ProjectDocumentation,
  options?: { title?: string; description?: string },
): string {
  const lines: string[] = [];
  const title = options?.title ?? "API Reference";
  const desc = options?.description ?? "Auto-generated by oxdoc";

  lines.push(`# ${title}`);
  lines.push("");
  lines.push(`> ${desc}`);
  lines.push("");

  for (const file of project.files) {
    const exported = file.symbols.filter((s) => s.exported);
    if (exported.length === 0) continue;
    lines.push(renderFileLlms(file, exported));
  }

  return lines.join("\n");
}

function renderFileLlms(
  file: FileDocumentation,
  symbols: DocumentedSymbol[],
): string {
  const lines: string[] = [];
  lines.push(`## ${file.filePath}`);
  lines.push("");

  for (const sym of symbols) {
    lines.push(renderSymbolLlms(sym));
  }

  return lines.join("\n");
}

function renderSymbolLlms(symbol: DocumentedSymbol): string {
  const lines: string[] = [];

  lines.push(`### ${symbol.signature || symbol.name}`);
  lines.push("");

  if (symbol.doc) {
    if (symbol.doc.description) {
      lines.push(symbol.doc.description);
      lines.push("");
    }

    const params = symbol.doc.tags.filter((t) => t.tag === "param");
    if (params.length > 0) {
      lines.push("Parameters:");
      for (const p of params) {
        const type = p.type ? ` (${p.type})` : "";
        lines.push(`- ${p.name}${type}: ${p.description}`);
      }
      lines.push("");
    }

    const returns = symbol.doc.tags.find(
      (t) => t.tag === "returns" || t.tag === "return",
    );
    if (returns) {
      const type = returns.type ? ` (${returns.type})` : "";
      lines.push(`Returns${type}: ${returns.description}`);
      lines.push("");
    }
  }

  if (symbol.children && symbol.children.length > 0) {
    lines.push("Members:");
    for (const child of symbol.children) {
      const desc = child.doc?.description ?? "";
      lines.push(`- ${child.name}: ${desc || child.signature}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
