import type {
  ProjectDocumentation,
  FileDocumentation,
  DocumentedSymbol,
  DocTag,
} from "../../types/index.js";

/**
 * 프로젝트 문서를 Markdown 문자열로 변환한다.
 * @param project - 프로젝트 문서 정보
 * @returns Markdown 문자열
 */
export function generateMarkdown(project: ProjectDocumentation): string {
  const lines: string[] = [];

  lines.push("# API Documentation\n");
  lines.push(
    `> Generated by oxdoc v${project.metadata.version} at ${project.metadata.generatedAt}\n`,
  );

  for (const file of project.files) {
    if (file.symbols.length === 0) continue;
    lines.push(renderFile(file));
  }

  return lines.join("\n");
}

function renderFile(file: FileDocumentation): string {
  const lines: string[] = [];
  lines.push(`## ${file.filePath}\n`);

  if (file.fileDoc) {
    lines.push(`${file.fileDoc.description}\n`);
  }

  const exported = file.symbols.filter((s) => s.exported);
  const internal = file.symbols.filter((s) => !s.exported);

  if (exported.length > 0) {
    for (const sym of exported) {
      lines.push(renderSymbol(sym));
    }
  }

  if (internal.length > 0) {
    lines.push("### Internal\n");
    for (const sym of internal) {
      lines.push(renderSymbol(sym));
    }
  }

  return lines.join("\n");
}

function renderSymbol(symbol: DocumentedSymbol, depth = 3): string {
  const lines: string[] = [];
  const prefix = "#".repeat(depth);

  lines.push(`${prefix} \`${symbol.signature || symbol.name}\`\n`);

  if (symbol.doc) {
    if (symbol.doc.description) {
      lines.push(`${symbol.doc.description}\n`);
    }

    const params = symbol.doc.tags.filter((t) => t.tag === "param");
    if (params.length > 0) {
      lines.push("**Parameters:**\n");
      lines.push("| Name | Type | Description |");
      lines.push("|------|------|-------------|");
      for (const p of params) {
        const type = p.type ? `\`${p.type}\`` : "-";
        lines.push(`| ${p.name} | ${type} | ${p.description} |`);
      }
      lines.push("");
    }

    const returns = symbol.doc.tags.find(
      (t) => t.tag === "returns" || t.tag === "return",
    );
    if (returns) {
      const type = returns.type ? `\`${returns.type}\`` : "";
      lines.push(`**Returns:** ${type} ${returns.description}\n`);
    }

    const examples = symbol.doc.tags.filter((t) => t.tag === "example");
    for (const ex of examples) {
      lines.push("**Example:**\n");
      lines.push(formatExample(ex));
    }
  }

  if (symbol.children && symbol.children.length > 0) {
    for (const child of symbol.children) {
      lines.push(renderSymbol(child, Math.min(depth + 1, 6)));
    }
  }

  return lines.join("\n");
}

function formatExample(tag: DocTag): string {
  const desc = tag.description.trim();
  // 이미 코드 블록으로 감싸져 있는지 확인
  if (desc.startsWith("```")) {
    return desc + "\n";
  }
  return `\`\`\`ts\n${desc}\n\`\`\`\n`;
}
